export { ReactComponent as Clock } from "../images/icons/clock.svg";
export { ReactComponent as Coin } from "../images/icons/coin.svg";
export { ReactComponent as Pizza } from "../images/icons/pizza.svg";
export { ReactComponent as Sparkles } from "../images/icons/sparkles.svg";
export { ReactComponent as ViewFilled } from "../images/icons/view--filled.svg";
export { ReactComponent as ViewOffFilled } from "../images/icons/view--off--filled.svg";
export { ReactComponent as GeniusFlash } from "../images/icons/genius-flash.svg";
export { ReactComponent as ArrowRight } from "images/icons/arrow-right.svg";
export { ReactComponent as Hearts } from "images/hearts.svg";
