version: '3.4'
services:
  redis:
    image: "redis/redis-stack-server:latest"
    volumes:
      - redis_data:/data
    environment:
      REDIS_ARGS: "--appendonly yes --aof-use-rdb-preamble yes"
  redisinsight:
    image: "redislabs/redisinsight:latest"
    volumes:
      - redisinsight_data:/db
  central:
    image: "ghcr.io/fnatte/pizza-tribes-central:latest"
    volumes:
      - central_data:/data
    env_file: .env
    environment:
      PORT: 8080
      SQLITE_DSN: /data/pizzatribes.db
  api:
    image: "ghcr.io/fnatte/pizza-tribes-api:latest"
    env_file: .env
    environment:
      PORT: 8080
      REDIS_ADDR: "redis:6379"
  gamelet:
    image: "ghcr.io/fnatte/pizza-tribes-gamelet:latest"
    env_file: .env
    environment:
      PORT: 8080
      REDIS_ADDR: "redis:6379"
  worker:
    image: "ghcr.io/fnatte/pizza-tribes-worker:latest"
    env_file: .env
    environment:
      REDIS_ADDR: "redis:6379"
    volumes:
     - ./service-account-file.json:/service-account-file.json
  updater:
    image: "ghcr.io/fnatte/pizza-tribes-updater:latest"
    environment:
      REDIS_ADDR: "redis:6379"
  webapp:
    image: "ghcr.io/fnatte/pizza-tribes-webapp:latest"
  migrator:
    image: "ghcr.io/fnatte/pizza-tribes-migrator:latest"
    volumes:
      - central_data:/data
    environment:
      REDIS_ADDR: "redis:6379"
      SQLITE_DSN: /data/pizzatribes.db
  front:
    image: "ghcr.io/fnatte/pizza-tribes-front:latest"
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - caddy_data:/data
  admin:
    image: "ghcr.io/fnatte/pizza-tribes-admin:latest"
    volumes:
      - central_data:/data
    environment:
      REDIS_ADDR: "redis:6379"
      SQLITE_DSN: /data/pizzatribes.db

volumes:
  redis_data:
  redisinsight_data:
  caddy_data:
  central_data:

