version: '3.4'
services:
  redis:
    image: "redis/redis-stack-server:latest"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: "--appendonly yes --aof-use-rdb-preamble yes"
  api:
    image: "ghcr.io/fnatte/pizza-tribes-api:latest"
    env_file: .env
    environment:
      PORT: 8080
      REDIS_ADDR: "redis:6379"
  worker:
    image: "ghcr.io/fnatte/pizza-tribes-worker:latest"
    environment:
      REDIS_ADDR: "redis:6379"
  updater:
    image: "ghcr.io/fnatte/pizza-tribes-updater:latest"
    environment:
      REDIS_ADDR: "redis:6379"
  webapp:
    image: "ghcr.io/fnatte/pizza-tribes-webapp:latest"
  migrator:
    image: "ghcr.io/fnatte/pizza-tribes-migrator:latest"
    environment:
      REDIS_ADDR: "redis:6379"
  front:
    image: "ghcr.io/fnatte/pizza-tribes-front:latest"
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - caddy_data:/data

volumes:
  redis_data:
  caddy_data:
