// Code generated by jtd-codegen for Go v0.2.1. DO NOT EDIT.

package gamestate

type GameStateConstructionQueue struct {
	Building Building `json:"building"`

	CompleteAt string `json:"completeAt"`

	Level int32 `json:"level"`

	LotID string `json:"lotId"`

	Razing bool `json:"razing"`
}

type GameStateLot struct {
	Building Building `json:"building"`

	Level int32 `json:"level"`

	Streak int32 `json:"streak"`

	TappedAt int32 `json:"tappedAt"`

	Taps int32 `json:"taps"`
}

type GameStateMouse struct {
	Education Education `json:"education"`

	IsBeingEducated bool `json:"isBeingEducated"`

	IsEducated bool `json:"isEducated"`

	Name string `json:"name"`
}

type GameStatePopulation struct {
	Chefs int32 `json:"chefs"`

	Guards int32 `json:"guards"`

	Publicists int32 `json:"publicists"`

	Salesmice int32 `json:"salesmice"`

	Thieves int32 `json:"thieves"`

	Uneducated int32 `json:"uneducated"`
}

type GameStateQuest struct {
	ClaimedReward bool `json:"claimedReward"`

	Completed bool `json:"completed"`

	Opened bool `json:"opened"`
}

type GameStateResearchQueue struct {
	CompleteAt string `json:"completeAt"`

	Discovery ResearchDiscovery `json:"discovery"`
}

type GameStateResources struct {
	Coins int32 `json:"coins"`

	Pizzas int32 `json:"pizzas"`
}

type GameState struct {
	ConstructionQueue []GameStateConstructionQueue `json:"constructionQueue"`

	Discoveries []ResearchDiscovery `json:"discoveries"`

	Lots map[string]GameStateLot `json:"lots"`

	Mice map[string]GameStateMouse `json:"mice"`

	Population GameStatePopulation `json:"population"`

	Quests map[string]GameStateQuest `json:"quests"`

	ResearchQueue []GameStateResearchQueue `json:"researchQueue"`

	Resources GameStateResources `json:"resources"`

	Timestamp string `json:"timestamp"`

	TownX int32 `json:"townX"`

	TownY int32 `json:"townY"`

	TrainingQueue []Training `json:"trainingQueue"`

	TravelQueue []Travel `json:"travelQueue"`
}

type Building string

const (
	BuildingHouse Building = "house"

	BuildingKitchen Building = "kitchen"

	BuildingMarketinghq Building = "marketinghq"

	BuildingResearchInstitute Building = "research_institute"

	BuildingSchool Building = "school"

	BuildingShop Building = "shop"

	BuildingTownCentre Building = "town_centre"
)

type Education string

const (
	EducationChef Education = "chef"

	EducationGuard Education = "guard"

	EducationPublicist Education = "publicist"

	EducationSalesmouse Education = "salesmouse"

	EducationThief Education = "thief"
)

type ResearchDiscovery string

const (
	ResearchDiscoveryDigitalOrderingSystem ResearchDiscovery = "digital_ordering_system"

	ResearchDiscoveryDoubleZeroFlour ResearchDiscovery = "double_zero_flour"

	ResearchDiscoveryDurumWheat ResearchDiscovery = "durum_wheat"

	ResearchDiscoveryExtraVirgin ResearchDiscovery = "extra_virgin"

	ResearchDiscoveryGasOven ResearchDiscovery = "gas_oven"

	ResearchDiscoveryHybridOven ResearchDiscovery = "hybrid_oven"

	ResearchDiscoveryMasonryOven ResearchDiscovery = "masonry_oven"

	ResearchDiscoveryMobileApp ResearchDiscovery = "mobile_app"

	ResearchDiscoveryOcimumBasilicum ResearchDiscovery = "ocimum_basilicum"

	ResearchDiscoverySanMarzanoTomatoes ResearchDiscovery = "san_marzano_tomatoes"

	ResearchDiscoveryWebsite ResearchDiscovery = "website"
)

type Stats struct {
	DemandOffpeak float64 `json:"demandOffpeak"`

	DemandRushHour float64 `json:"demandRushHour"`

	EmployedChefs int32 `json:"employedChefs"`

	EmployedSalesmice int32 `json:"employedSalesmice"`

	MaxSellsByMicePerSecond float64 `json:"maxSellsByMicePerSecond"`

	PizzasProducedPerSecond float64 `json:"pizzasProducedPerSecond"`
}

type Training struct {
	Amount int32 `json:"amount"`

	CompleteAt string `json:"completeAt"`

	Education Education `json:"education"`
}

type Travel struct {
	ArrivalAt string `json:"arrivalAt"`

	Coins string `json:"coins"`

	DestinationX int32 `json:"destinationX"`

	DestinationY int32 `json:"destinationY"`

	Returning bool `json:"returning"`

	Thieves int32 `json:"thieves"`
}
