// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.21.9
// source: appearance.proto

package models

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AppearanceCategory int32

const (
	AppearanceCategory_BODY        AppearanceCategory = 0
	AppearanceCategory_EYES        AppearanceCategory = 1
	AppearanceCategory_MOUTH       AppearanceCategory = 2
	AppearanceCategory_FEET        AppearanceCategory = 3
	AppearanceCategory_TAIL        AppearanceCategory = 4
	AppearanceCategory_OUTFIT      AppearanceCategory = 5
	AppearanceCategory_EYES_EXTRA1 AppearanceCategory = 6
	AppearanceCategory_EYES_EXTRA2 AppearanceCategory = 7
	AppearanceCategory_HAT         AppearanceCategory = 8
	AppearanceCategory_LEFT_HAND   AppearanceCategory = 9
	AppearanceCategory_RIGHT_HAND  AppearanceCategory = 10
)

// Enum value maps for AppearanceCategory.
var (
	AppearanceCategory_name = map[int32]string{
		0:  "BODY",
		1:  "EYES",
		2:  "MOUTH",
		3:  "FEET",
		4:  "TAIL",
		5:  "OUTFIT",
		6:  "EYES_EXTRA1",
		7:  "EYES_EXTRA2",
		8:  "HAT",
		9:  "LEFT_HAND",
		10: "RIGHT_HAND",
	}
	AppearanceCategory_value = map[string]int32{
		"BODY":        0,
		"EYES":        1,
		"MOUTH":       2,
		"FEET":        3,
		"TAIL":        4,
		"OUTFIT":      5,
		"EYES_EXTRA1": 6,
		"EYES_EXTRA2": 7,
		"HAT":         8,
		"LEFT_HAND":   9,
		"RIGHT_HAND":  10,
	}
)

func (x AppearanceCategory) Enum() *AppearanceCategory {
	p := new(AppearanceCategory)
	*p = x
	return p
}

func (x AppearanceCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppearanceCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_appearance_proto_enumTypes[0].Descriptor()
}

func (AppearanceCategory) Type() protoreflect.EnumType {
	return &file_appearance_proto_enumTypes[0]
}

func (x AppearanceCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppearanceCategory.Descriptor instead.
func (AppearanceCategory) EnumDescriptor() ([]byte, []int) {
	return file_appearance_proto_rawDescGZIP(), []int{0}
}

type AppearancePart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category AppearanceCategory `protobuf:"varint,2,opt,name=category,proto3,enum=pizzatribes.AppearanceCategory" json:"category,omitempty"`
	Free     bool               `protobuf:"varint,3,opt,name=free,proto3" json:"free,omitempty"`
}

func (x *AppearancePart) Reset() {
	*x = AppearancePart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appearance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppearancePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearancePart) ProtoMessage() {}

func (x *AppearancePart) ProtoReflect() protoreflect.Message {
	mi := &file_appearance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearancePart.ProtoReflect.Descriptor instead.
func (*AppearancePart) Descriptor() ([]byte, []int) {
	return file_appearance_proto_rawDescGZIP(), []int{0}
}

func (x *AppearancePart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppearancePart) GetCategory() AppearanceCategory {
	if x != nil {
		return x.Category
	}
	return AppearanceCategory_BODY
}

func (x *AppearancePart) GetFree() bool {
	if x != nil {
		return x.Free
	}
	return false
}

type MouseAppearance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parts map[int32]*MouseAppearance_PartRef `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MouseAppearance) Reset() {
	*x = MouseAppearance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appearance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MouseAppearance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseAppearance) ProtoMessage() {}

func (x *MouseAppearance) ProtoReflect() protoreflect.Message {
	mi := &file_appearance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseAppearance.ProtoReflect.Descriptor instead.
func (*MouseAppearance) Descriptor() ([]byte, []int) {
	return file_appearance_proto_rawDescGZIP(), []int{1}
}

func (x *MouseAppearance) GetParts() map[int32]*MouseAppearance_PartRef {
	if x != nil {
		return x.Parts
	}
	return nil
}

type MouseAppearance_PartRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Color int32  `protobuf:"varint,2,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *MouseAppearance_PartRef) Reset() {
	*x = MouseAppearance_PartRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appearance_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MouseAppearance_PartRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseAppearance_PartRef) ProtoMessage() {}

func (x *MouseAppearance_PartRef) ProtoReflect() protoreflect.Message {
	mi := &file_appearance_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseAppearance_PartRef.ProtoReflect.Descriptor instead.
func (*MouseAppearance_PartRef) Descriptor() ([]byte, []int) {
	return file_appearance_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MouseAppearance_PartRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MouseAppearance_PartRef) GetColor() int32 {
	if x != nil {
		return x.Color
	}
	return 0
}

var File_appearance_proto protoreflect.FileDescriptor

var file_appearance_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x70, 0x65, 0x61, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x22,
	0x71, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x65, 0x61, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x50, 0x61, 0x72,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x3b, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65,
	0x73, 0x2e, 0x41, 0x70, 0x70, 0x65, 0x61, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x72, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x72,
	0x65, 0x65, 0x22, 0xe1, 0x01, 0x0a, 0x0f, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x70, 0x70, 0x65,
	0x61, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69,
	0x62, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x70, 0x70, 0x65, 0x61, 0x72, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05,
	0x70, 0x61, 0x72, 0x74, 0x73, 0x1a, 0x2f, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x66,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x1a, 0x5e, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x74, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69,
	0x62, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x70, 0x70, 0x65, 0x61, 0x72, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x66, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x9d, 0x01, 0x0a, 0x12, 0x41, 0x70, 0x70, 0x65, 0x61,
	0x72, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x08, 0x0a,
	0x04, 0x42, 0x4f, 0x44, 0x59, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x59, 0x45, 0x53, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x4f, 0x55, 0x54, 0x48, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x46, 0x45, 0x45, 0x54, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x41, 0x49, 0x4c, 0x10, 0x04,
	0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x55, 0x54, 0x46, 0x49, 0x54, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b,
	0x45, 0x59, 0x45, 0x53, 0x5f, 0x45, 0x58, 0x54, 0x52, 0x41, 0x31, 0x10, 0x06, 0x12, 0x0f, 0x0a,
	0x0b, 0x45, 0x59, 0x45, 0x53, 0x5f, 0x45, 0x58, 0x54, 0x52, 0x41, 0x32, 0x10, 0x07, 0x12, 0x07,
	0x0a, 0x03, 0x48, 0x41, 0x54, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x45, 0x46, 0x54, 0x5f,
	0x48, 0x41, 0x4e, 0x44, 0x10, 0x09, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x49, 0x47, 0x48, 0x54, 0x5f,
	0x48, 0x41, 0x4e, 0x44, 0x10, 0x0a, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6e, 0x61, 0x74, 0x74, 0x65, 0x2f, 0x70, 0x69, 0x7a, 0x7a,
	0x61, 0x2d, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_appearance_proto_rawDescOnce sync.Once
	file_appearance_proto_rawDescData = file_appearance_proto_rawDesc
)

func file_appearance_proto_rawDescGZIP() []byte {
	file_appearance_proto_rawDescOnce.Do(func() {
		file_appearance_proto_rawDescData = protoimpl.X.CompressGZIP(file_appearance_proto_rawDescData)
	})
	return file_appearance_proto_rawDescData
}

var file_appearance_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_appearance_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_appearance_proto_goTypes = []interface{}{
	(AppearanceCategory)(0),         // 0: pizzatribes.AppearanceCategory
	(*AppearancePart)(nil),          // 1: pizzatribes.AppearancePart
	(*MouseAppearance)(nil),         // 2: pizzatribes.MouseAppearance
	(*MouseAppearance_PartRef)(nil), // 3: pizzatribes.MouseAppearance.PartRef
	nil,                             // 4: pizzatribes.MouseAppearance.PartsEntry
}
var file_appearance_proto_depIdxs = []int32{
	0, // 0: pizzatribes.AppearancePart.category:type_name -> pizzatribes.AppearanceCategory
	4, // 1: pizzatribes.MouseAppearance.parts:type_name -> pizzatribes.MouseAppearance.PartsEntry
	3, // 2: pizzatribes.MouseAppearance.PartsEntry.value:type_name -> pizzatribes.MouseAppearance.PartRef
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_appearance_proto_init() }
func file_appearance_proto_init() {
	if File_appearance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_appearance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppearancePart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appearance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MouseAppearance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appearance_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MouseAppearance_PartRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_appearance_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_appearance_proto_goTypes,
		DependencyIndexes: file_appearance_proto_depIdxs,
		EnumInfos:         file_appearance_proto_enumTypes,
		MessageInfos:      file_appearance_proto_msgTypes,
	}.Build()
	File_appearance_proto = out.File
	file_appearance_proto_rawDesc = nil
	file_appearance_proto_goTypes = nil
	file_appearance_proto_depIdxs = nil
}
