// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.21.1
// source: building.proto

package models

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Building int32

const (
	Building_KITCHEN            Building = 0
	Building_SHOP               Building = 1
	Building_HOUSE              Building = 2
	Building_SCHOOL             Building = 3
	Building_MARKETINGHQ        Building = 4
	Building_RESEARCH_INSTITUTE Building = 5
	Building_TOWN_CENTRE        Building = 6
)

// Enum value maps for Building.
var (
	Building_name = map[int32]string{
		0: "KITCHEN",
		1: "SHOP",
		2: "HOUSE",
		3: "SCHOOL",
		4: "MARKETINGHQ",
		5: "RESEARCH_INSTITUTE",
		6: "TOWN_CENTRE",
	}
	Building_value = map[string]int32{
		"KITCHEN":            0,
		"SHOP":               1,
		"HOUSE":              2,
		"SCHOOL":             3,
		"MARKETINGHQ":        4,
		"RESEARCH_INSTITUTE": 5,
		"TOWN_CENTRE":        6,
	}
)

func (x Building) Enum() *Building {
	p := new(Building)
	*p = x
	return p
}

func (x Building) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Building) Descriptor() protoreflect.EnumDescriptor {
	return file_building_proto_enumTypes[0].Descriptor()
}

func (Building) Type() protoreflect.EnumType {
	return &file_building_proto_enumTypes[0]
}

func (x Building) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Building.Descriptor instead.
func (Building) EnumDescriptor() ([]byte, []int) {
	return file_building_proto_rawDescGZIP(), []int{0}
}

type Employer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxWorkforce int32 `protobuf:"varint,1,opt,name=maxWorkforce,proto3" json:"maxWorkforce,omitempty"`
}

func (x *Employer) Reset() {
	*x = Employer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_building_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Employer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employer) ProtoMessage() {}

func (x *Employer) ProtoReflect() protoreflect.Message {
	mi := &file_building_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employer.ProtoReflect.Descriptor instead.
func (*Employer) Descriptor() ([]byte, []int) {
	return file_building_proto_rawDescGZIP(), []int{0}
}

func (x *Employer) GetMaxWorkforce() int32 {
	if x != nil {
		return x.MaxWorkforce
	}
	return 0
}

type Residence struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beds int32 `protobuf:"varint,1,opt,name=beds,proto3" json:"beds,omitempty"`
}

func (x *Residence) Reset() {
	*x = Residence{}
	if protoimpl.UnsafeEnabled {
		mi := &file_building_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Residence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Residence) ProtoMessage() {}

func (x *Residence) ProtoReflect() protoreflect.Message {
	mi := &file_building_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Residence.ProtoReflect.Descriptor instead.
func (*Residence) Descriptor() ([]byte, []int) {
	return file_building_proto_rawDescGZIP(), []int{1}
}

func (x *Residence) GetBeds() int32 {
	if x != nil {
		return x.Beds
	}
	return 0
}

type BuildingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string                    `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	TitlePlural string                    `protobuf:"bytes,2,opt,name=titlePlural,proto3" json:"titlePlural,omitempty"`
	LevelInfos  []*BuildingInfo_LevelInfo `protobuf:"bytes,3,rep,name=levelInfos,proto3" json:"levelInfos,omitempty"`
	MaxCount    *wrapperspb.Int32Value    `protobuf:"bytes,4,opt,name=maxCount,proto3" json:"maxCount,omitempty"`
}

func (x *BuildingInfo) Reset() {
	*x = BuildingInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_building_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingInfo) ProtoMessage() {}

func (x *BuildingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_building_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingInfo.ProtoReflect.Descriptor instead.
func (*BuildingInfo) Descriptor() ([]byte, []int) {
	return file_building_proto_rawDescGZIP(), []int{2}
}

func (x *BuildingInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BuildingInfo) GetTitlePlural() string {
	if x != nil {
		return x.TitlePlural
	}
	return ""
}

func (x *BuildingInfo) GetLevelInfos() []*BuildingInfo_LevelInfo {
	if x != nil {
		return x.LevelInfos
	}
	return nil
}

func (x *BuildingInfo) GetMaxCount() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxCount
	}
	return nil
}

type BuildingInfo_LevelInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cost                  int32                  `protobuf:"varint,1,opt,name=cost,proto3" json:"cost,omitempty"`
	ConstructionTime      int32                  `protobuf:"varint,2,opt,name=constructionTime,proto3" json:"constructionTime,omitempty"`
	Employer              *Employer              `protobuf:"bytes,3,opt,name=employer,proto3" json:"employer,omitempty"`
	Residence             *Residence             `protobuf:"bytes,4,opt,name=residence,proto3" json:"residence,omitempty"`
	FirstCost             *wrapperspb.Int32Value `protobuf:"bytes,5,opt,name=firstCost,proto3" json:"firstCost,omitempty"`
	FirstConstructionTime *wrapperspb.Int32Value `protobuf:"bytes,6,opt,name=firstConstructionTime,proto3" json:"firstConstructionTime,omitempty"`
	Description           string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *BuildingInfo_LevelInfo) Reset() {
	*x = BuildingInfo_LevelInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_building_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildingInfo_LevelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingInfo_LevelInfo) ProtoMessage() {}

func (x *BuildingInfo_LevelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_building_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingInfo_LevelInfo.ProtoReflect.Descriptor instead.
func (*BuildingInfo_LevelInfo) Descriptor() ([]byte, []int) {
	return file_building_proto_rawDescGZIP(), []int{2, 0}
}

func (x *BuildingInfo_LevelInfo) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *BuildingInfo_LevelInfo) GetConstructionTime() int32 {
	if x != nil {
		return x.ConstructionTime
	}
	return 0
}

func (x *BuildingInfo_LevelInfo) GetEmployer() *Employer {
	if x != nil {
		return x.Employer
	}
	return nil
}

func (x *BuildingInfo_LevelInfo) GetResidence() *Residence {
	if x != nil {
		return x.Residence
	}
	return nil
}

func (x *BuildingInfo_LevelInfo) GetFirstCost() *wrapperspb.Int32Value {
	if x != nil {
		return x.FirstCost
	}
	return nil
}

func (x *BuildingInfo_LevelInfo) GetFirstConstructionTime() *wrapperspb.Int32Value {
	if x != nil {
		return x.FirstConstructionTime
	}
	return nil
}

func (x *BuildingInfo_LevelInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_building_proto protoreflect.FileDescriptor

var file_building_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x1a, 0x1e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a,
	0x08, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x78,
	0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x6d, 0x61, 0x78, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x22, 0x1f, 0x0a,
	0x09, 0x52, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x65,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x62, 0x65, 0x64, 0x73, 0x22, 0xab,
	0x04, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x50, 0x6c,
	0x75, 0x72, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x50, 0x6c, 0x75, 0x72, 0x61, 0x6c, 0x12, 0x43, 0x0a, 0x0a, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x69,
	0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69,
	0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0a, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x37, 0x0a, 0x08,
	0x6d, 0x61, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x08, 0x6d, 0x61, 0x78,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0xe4, 0x02, 0x0a, 0x09, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69,
	0x62, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x52, 0x08, 0x65, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x69, 0x64, 0x65,
	0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x69, 0x7a, 0x7a,
	0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x63,
	0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x09,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x43, 0x6f, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x51, 0x0a, 0x15, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x15, 0x66, 0x69, 0x72, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x72, 0x0a, 0x08,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x0b, 0x0a, 0x07, 0x4b, 0x49, 0x54, 0x43,
	0x48, 0x45, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x48, 0x4f, 0x50, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x48, 0x4f, 0x55, 0x53, 0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x43,
	0x48, 0x4f, 0x4f, 0x4c, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54,
	0x49, 0x4e, 0x47, 0x48, 0x51, 0x10, 0x04, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x53, 0x45, 0x41,
	0x52, 0x43, 0x48, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x49, 0x54, 0x55, 0x54, 0x45, 0x10, 0x05, 0x12,
	0x0f, 0x0a, 0x0b, 0x54, 0x4f, 0x57, 0x4e, 0x5f, 0x43, 0x45, 0x4e, 0x54, 0x52, 0x45, 0x10, 0x06,
	0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66,
	0x6e, 0x61, 0x74, 0x74, 0x65, 0x2f, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x2d, 0x74, 0x72, 0x69, 0x62,
	0x65, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_building_proto_rawDescOnce sync.Once
	file_building_proto_rawDescData = file_building_proto_rawDesc
)

func file_building_proto_rawDescGZIP() []byte {
	file_building_proto_rawDescOnce.Do(func() {
		file_building_proto_rawDescData = protoimpl.X.CompressGZIP(file_building_proto_rawDescData)
	})
	return file_building_proto_rawDescData
}

var file_building_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_building_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_building_proto_goTypes = []interface{}{
	(Building)(0),                  // 0: pizzatribes.Building
	(*Employer)(nil),               // 1: pizzatribes.Employer
	(*Residence)(nil),              // 2: pizzatribes.Residence
	(*BuildingInfo)(nil),           // 3: pizzatribes.BuildingInfo
	(*BuildingInfo_LevelInfo)(nil), // 4: pizzatribes.BuildingInfo.LevelInfo
	(*wrapperspb.Int32Value)(nil),  // 5: google.protobuf.Int32Value
}
var file_building_proto_depIdxs = []int32{
	4, // 0: pizzatribes.BuildingInfo.levelInfos:type_name -> pizzatribes.BuildingInfo.LevelInfo
	5, // 1: pizzatribes.BuildingInfo.maxCount:type_name -> google.protobuf.Int32Value
	1, // 2: pizzatribes.BuildingInfo.LevelInfo.employer:type_name -> pizzatribes.Employer
	2, // 3: pizzatribes.BuildingInfo.LevelInfo.residence:type_name -> pizzatribes.Residence
	5, // 4: pizzatribes.BuildingInfo.LevelInfo.firstCost:type_name -> google.protobuf.Int32Value
	5, // 5: pizzatribes.BuildingInfo.LevelInfo.firstConstructionTime:type_name -> google.protobuf.Int32Value
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_building_proto_init() }
func file_building_proto_init() {
	if File_building_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_building_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Employer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_building_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Residence); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_building_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildingInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_building_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildingInfo_LevelInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_building_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_building_proto_goTypes,
		DependencyIndexes: file_building_proto_depIdxs,
		EnumInfos:         file_building_proto_enumTypes,
		MessageInfos:      file_building_proto_msgTypes,
	}.Build()
	File_building_proto = out.File
	file_building_proto_rawDesc = nil
	file_building_proto_goTypes = nil
	file_building_proto_depIdxs = nil
}
