// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.21.4
// source: client_message.proto

package models

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Type:
	//	*ClientMessage_Tap_
	//	*ClientMessage_ConstructBuilding_
	//	*ClientMessage_UpgradeBuilding_
	//	*ClientMessage_Train_
	//	*ClientMessage_Expand_
	//	*ClientMessage_Steal_
	//	*ClientMessage_ReadReport_
	//	*ClientMessage_RazeBuilding_
	//	*ClientMessage_StartResearch_
	//	*ClientMessage_CancelRazeBuilding_
	//	*ClientMessage_ReschoolMouse_
	//	*ClientMessage_RenameMouse_
	//	*ClientMessage_OpenQuest_
	//	*ClientMessage_ClaimQuestReward_
	//	*ClientMessage_CompleteQuest_
	//	*ClientMessage_ReportActivity_
	//	*ClientMessage_SaveMouseAppearance_
	//	*ClientMessage_SetAmbassadorMouse_
	//	*ClientMessage_SetPizzaPrice_
	//	*ClientMessage_BuyGeniusFlash_
	Type isClientMessage_Type `protobuf_oneof:"type"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (m *ClientMessage) GetType() isClientMessage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *ClientMessage) GetTap() *ClientMessage_Tap {
	if x, ok := x.GetType().(*ClientMessage_Tap_); ok {
		return x.Tap
	}
	return nil
}

func (x *ClientMessage) GetConstructBuilding() *ClientMessage_ConstructBuilding {
	if x, ok := x.GetType().(*ClientMessage_ConstructBuilding_); ok {
		return x.ConstructBuilding
	}
	return nil
}

func (x *ClientMessage) GetUpgradeBuilding() *ClientMessage_UpgradeBuilding {
	if x, ok := x.GetType().(*ClientMessage_UpgradeBuilding_); ok {
		return x.UpgradeBuilding
	}
	return nil
}

func (x *ClientMessage) GetTrain() *ClientMessage_Train {
	if x, ok := x.GetType().(*ClientMessage_Train_); ok {
		return x.Train
	}
	return nil
}

func (x *ClientMessage) GetExpand() *ClientMessage_Expand {
	if x, ok := x.GetType().(*ClientMessage_Expand_); ok {
		return x.Expand
	}
	return nil
}

func (x *ClientMessage) GetSteal() *ClientMessage_Steal {
	if x, ok := x.GetType().(*ClientMessage_Steal_); ok {
		return x.Steal
	}
	return nil
}

func (x *ClientMessage) GetReadReport() *ClientMessage_ReadReport {
	if x, ok := x.GetType().(*ClientMessage_ReadReport_); ok {
		return x.ReadReport
	}
	return nil
}

func (x *ClientMessage) GetRazeBuilding() *ClientMessage_RazeBuilding {
	if x, ok := x.GetType().(*ClientMessage_RazeBuilding_); ok {
		return x.RazeBuilding
	}
	return nil
}

func (x *ClientMessage) GetStartResearch() *ClientMessage_StartResearch {
	if x, ok := x.GetType().(*ClientMessage_StartResearch_); ok {
		return x.StartResearch
	}
	return nil
}

func (x *ClientMessage) GetCancelRazeBuilding() *ClientMessage_CancelRazeBuilding {
	if x, ok := x.GetType().(*ClientMessage_CancelRazeBuilding_); ok {
		return x.CancelRazeBuilding
	}
	return nil
}

func (x *ClientMessage) GetReschoolMouse() *ClientMessage_ReschoolMouse {
	if x, ok := x.GetType().(*ClientMessage_ReschoolMouse_); ok {
		return x.ReschoolMouse
	}
	return nil
}

func (x *ClientMessage) GetRenameMouse() *ClientMessage_RenameMouse {
	if x, ok := x.GetType().(*ClientMessage_RenameMouse_); ok {
		return x.RenameMouse
	}
	return nil
}

func (x *ClientMessage) GetOpenQuest() *ClientMessage_OpenQuest {
	if x, ok := x.GetType().(*ClientMessage_OpenQuest_); ok {
		return x.OpenQuest
	}
	return nil
}

func (x *ClientMessage) GetClaimQuestReward() *ClientMessage_ClaimQuestReward {
	if x, ok := x.GetType().(*ClientMessage_ClaimQuestReward_); ok {
		return x.ClaimQuestReward
	}
	return nil
}

func (x *ClientMessage) GetCompleteQuest() *ClientMessage_CompleteQuest {
	if x, ok := x.GetType().(*ClientMessage_CompleteQuest_); ok {
		return x.CompleteQuest
	}
	return nil
}

func (x *ClientMessage) GetReportActivity() *ClientMessage_ReportActivity {
	if x, ok := x.GetType().(*ClientMessage_ReportActivity_); ok {
		return x.ReportActivity
	}
	return nil
}

func (x *ClientMessage) GetSaveMouseAppearance() *ClientMessage_SaveMouseAppearance {
	if x, ok := x.GetType().(*ClientMessage_SaveMouseAppearance_); ok {
		return x.SaveMouseAppearance
	}
	return nil
}

func (x *ClientMessage) GetSetAmbassadorMouse() *ClientMessage_SetAmbassadorMouse {
	if x, ok := x.GetType().(*ClientMessage_SetAmbassadorMouse_); ok {
		return x.SetAmbassadorMouse
	}
	return nil
}

func (x *ClientMessage) GetSetPizzaPrice() *ClientMessage_SetPizzaPrice {
	if x, ok := x.GetType().(*ClientMessage_SetPizzaPrice_); ok {
		return x.SetPizzaPrice
	}
	return nil
}

func (x *ClientMessage) GetBuyGeniusFlash() *ClientMessage_BuyGeniusFlash {
	if x, ok := x.GetType().(*ClientMessage_BuyGeniusFlash_); ok {
		return x.BuyGeniusFlash
	}
	return nil
}

type isClientMessage_Type interface {
	isClientMessage_Type()
}

type ClientMessage_Tap_ struct {
	Tap *ClientMessage_Tap `protobuf:"bytes,2,opt,name=tap,proto3,oneof"`
}

type ClientMessage_ConstructBuilding_ struct {
	ConstructBuilding *ClientMessage_ConstructBuilding `protobuf:"bytes,3,opt,name=constructBuilding,proto3,oneof"`
}

type ClientMessage_UpgradeBuilding_ struct {
	UpgradeBuilding *ClientMessage_UpgradeBuilding `protobuf:"bytes,4,opt,name=upgradeBuilding,proto3,oneof"`
}

type ClientMessage_Train_ struct {
	Train *ClientMessage_Train `protobuf:"bytes,5,opt,name=train,proto3,oneof"`
}

type ClientMessage_Expand_ struct {
	Expand *ClientMessage_Expand `protobuf:"bytes,6,opt,name=expand,proto3,oneof"`
}

type ClientMessage_Steal_ struct {
	Steal *ClientMessage_Steal `protobuf:"bytes,7,opt,name=steal,proto3,oneof"`
}

type ClientMessage_ReadReport_ struct {
	ReadReport *ClientMessage_ReadReport `protobuf:"bytes,8,opt,name=readReport,proto3,oneof"`
}

type ClientMessage_RazeBuilding_ struct {
	RazeBuilding *ClientMessage_RazeBuilding `protobuf:"bytes,9,opt,name=razeBuilding,proto3,oneof"`
}

type ClientMessage_StartResearch_ struct {
	StartResearch *ClientMessage_StartResearch `protobuf:"bytes,10,opt,name=startResearch,proto3,oneof"`
}

type ClientMessage_CancelRazeBuilding_ struct {
	CancelRazeBuilding *ClientMessage_CancelRazeBuilding `protobuf:"bytes,11,opt,name=cancelRazeBuilding,proto3,oneof"`
}

type ClientMessage_ReschoolMouse_ struct {
	ReschoolMouse *ClientMessage_ReschoolMouse `protobuf:"bytes,12,opt,name=reschoolMouse,proto3,oneof"`
}

type ClientMessage_RenameMouse_ struct {
	RenameMouse *ClientMessage_RenameMouse `protobuf:"bytes,13,opt,name=renameMouse,proto3,oneof"`
}

type ClientMessage_OpenQuest_ struct {
	OpenQuest *ClientMessage_OpenQuest `protobuf:"bytes,14,opt,name=openQuest,proto3,oneof"`
}

type ClientMessage_ClaimQuestReward_ struct {
	ClaimQuestReward *ClientMessage_ClaimQuestReward `protobuf:"bytes,15,opt,name=claimQuestReward,proto3,oneof"`
}

type ClientMessage_CompleteQuest_ struct {
	CompleteQuest *ClientMessage_CompleteQuest `protobuf:"bytes,16,opt,name=completeQuest,proto3,oneof"`
}

type ClientMessage_ReportActivity_ struct {
	ReportActivity *ClientMessage_ReportActivity `protobuf:"bytes,17,opt,name=reportActivity,proto3,oneof"`
}

type ClientMessage_SaveMouseAppearance_ struct {
	SaveMouseAppearance *ClientMessage_SaveMouseAppearance `protobuf:"bytes,18,opt,name=saveMouseAppearance,proto3,oneof"`
}

type ClientMessage_SetAmbassadorMouse_ struct {
	SetAmbassadorMouse *ClientMessage_SetAmbassadorMouse `protobuf:"bytes,19,opt,name=setAmbassadorMouse,proto3,oneof"`
}

type ClientMessage_SetPizzaPrice_ struct {
	SetPizzaPrice *ClientMessage_SetPizzaPrice `protobuf:"bytes,20,opt,name=setPizzaPrice,proto3,oneof"`
}

type ClientMessage_BuyGeniusFlash_ struct {
	BuyGeniusFlash *ClientMessage_BuyGeniusFlash `protobuf:"bytes,21,opt,name=buyGeniusFlash,proto3,oneof"`
}

func (*ClientMessage_Tap_) isClientMessage_Type() {}

func (*ClientMessage_ConstructBuilding_) isClientMessage_Type() {}

func (*ClientMessage_UpgradeBuilding_) isClientMessage_Type() {}

func (*ClientMessage_Train_) isClientMessage_Type() {}

func (*ClientMessage_Expand_) isClientMessage_Type() {}

func (*ClientMessage_Steal_) isClientMessage_Type() {}

func (*ClientMessage_ReadReport_) isClientMessage_Type() {}

func (*ClientMessage_RazeBuilding_) isClientMessage_Type() {}

func (*ClientMessage_StartResearch_) isClientMessage_Type() {}

func (*ClientMessage_CancelRazeBuilding_) isClientMessage_Type() {}

func (*ClientMessage_ReschoolMouse_) isClientMessage_Type() {}

func (*ClientMessage_RenameMouse_) isClientMessage_Type() {}

func (*ClientMessage_OpenQuest_) isClientMessage_Type() {}

func (*ClientMessage_ClaimQuestReward_) isClientMessage_Type() {}

func (*ClientMessage_CompleteQuest_) isClientMessage_Type() {}

func (*ClientMessage_ReportActivity_) isClientMessage_Type() {}

func (*ClientMessage_SaveMouseAppearance_) isClientMessage_Type() {}

func (*ClientMessage_SetAmbassadorMouse_) isClientMessage_Type() {}

func (*ClientMessage_SetPizzaPrice_) isClientMessage_Type() {}

func (*ClientMessage_BuyGeniusFlash_) isClientMessage_Type() {}

type ClientMessage_Tap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LotId string `protobuf:"bytes,1,opt,name=lotId,proto3" json:"lotId,omitempty"`
}

func (x *ClientMessage_Tap) Reset() {
	*x = ClientMessage_Tap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_Tap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_Tap) ProtoMessage() {}

func (x *ClientMessage_Tap) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_Tap.ProtoReflect.Descriptor instead.
func (*ClientMessage_Tap) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ClientMessage_Tap) GetLotId() string {
	if x != nil {
		return x.LotId
	}
	return ""
}

type ClientMessage_ConstructBuilding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LotId    string   `protobuf:"bytes,1,opt,name=lotId,proto3" json:"lotId,omitempty"`
	Building Building `protobuf:"varint,2,opt,name=building,proto3,enum=pizzatribes.Building" json:"building,omitempty"`
}

func (x *ClientMessage_ConstructBuilding) Reset() {
	*x = ClientMessage_ConstructBuilding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_ConstructBuilding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_ConstructBuilding) ProtoMessage() {}

func (x *ClientMessage_ConstructBuilding) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_ConstructBuilding.ProtoReflect.Descriptor instead.
func (*ClientMessage_ConstructBuilding) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ClientMessage_ConstructBuilding) GetLotId() string {
	if x != nil {
		return x.LotId
	}
	return ""
}

func (x *ClientMessage_ConstructBuilding) GetBuilding() Building {
	if x != nil {
		return x.Building
	}
	return Building_KITCHEN
}

type ClientMessage_UpgradeBuilding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LotId string `protobuf:"bytes,1,opt,name=lotId,proto3" json:"lotId,omitempty"`
}

func (x *ClientMessage_UpgradeBuilding) Reset() {
	*x = ClientMessage_UpgradeBuilding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_UpgradeBuilding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_UpgradeBuilding) ProtoMessage() {}

func (x *ClientMessage_UpgradeBuilding) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_UpgradeBuilding.ProtoReflect.Descriptor instead.
func (*ClientMessage_UpgradeBuilding) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ClientMessage_UpgradeBuilding) GetLotId() string {
	if x != nil {
		return x.LotId
	}
	return ""
}

type ClientMessage_RazeBuilding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LotId string `protobuf:"bytes,1,opt,name=lotId,proto3" json:"lotId,omitempty"`
}

func (x *ClientMessage_RazeBuilding) Reset() {
	*x = ClientMessage_RazeBuilding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_RazeBuilding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_RazeBuilding) ProtoMessage() {}

func (x *ClientMessage_RazeBuilding) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_RazeBuilding.ProtoReflect.Descriptor instead.
func (*ClientMessage_RazeBuilding) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ClientMessage_RazeBuilding) GetLotId() string {
	if x != nil {
		return x.LotId
	}
	return ""
}

type ClientMessage_CancelRazeBuilding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LotId string `protobuf:"bytes,1,opt,name=lotId,proto3" json:"lotId,omitempty"`
}

func (x *ClientMessage_CancelRazeBuilding) Reset() {
	*x = ClientMessage_CancelRazeBuilding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_CancelRazeBuilding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_CancelRazeBuilding) ProtoMessage() {}

func (x *ClientMessage_CancelRazeBuilding) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_CancelRazeBuilding.ProtoReflect.Descriptor instead.
func (*ClientMessage_CancelRazeBuilding) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 4}
}

func (x *ClientMessage_CancelRazeBuilding) GetLotId() string {
	if x != nil {
		return x.LotId
	}
	return ""
}

type ClientMessage_Train struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Education Education `protobuf:"varint,1,opt,name=education,proto3,enum=pizzatribes.Education" json:"education,omitempty"`
	Amount    int32     `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *ClientMessage_Train) Reset() {
	*x = ClientMessage_Train{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_Train) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_Train) ProtoMessage() {}

func (x *ClientMessage_Train) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_Train.ProtoReflect.Descriptor instead.
func (*ClientMessage_Train) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 5}
}

func (x *ClientMessage_Train) GetEducation() Education {
	if x != nil {
		return x.Education
	}
	return Education_CHEF
}

func (x *ClientMessage_Train) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ClientMessage_Expand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientMessage_Expand) Reset() {
	*x = ClientMessage_Expand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_Expand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_Expand) ProtoMessage() {}

func (x *ClientMessage_Expand) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_Expand.ProtoReflect.Descriptor instead.
func (*ClientMessage_Expand) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 6}
}

type ClientMessage_Steal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int32 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	X      int32 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y      int32 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *ClientMessage_Steal) Reset() {
	*x = ClientMessage_Steal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_Steal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_Steal) ProtoMessage() {}

func (x *ClientMessage_Steal) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_Steal.ProtoReflect.Descriptor instead.
func (*ClientMessage_Steal) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 7}
}

func (x *ClientMessage_Steal) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ClientMessage_Steal) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ClientMessage_Steal) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type ClientMessage_ReadReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClientMessage_ReadReport) Reset() {
	*x = ClientMessage_ReadReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_ReadReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_ReadReport) ProtoMessage() {}

func (x *ClientMessage_ReadReport) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_ReadReport.ProtoReflect.Descriptor instead.
func (*ClientMessage_ReadReport) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 8}
}

func (x *ClientMessage_ReadReport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ClientMessage_StartResearch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Discovery ResearchDiscovery `protobuf:"varint,1,opt,name=discovery,proto3,enum=pizzatribes.ResearchDiscovery" json:"discovery,omitempty"`
}

func (x *ClientMessage_StartResearch) Reset() {
	*x = ClientMessage_StartResearch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_StartResearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_StartResearch) ProtoMessage() {}

func (x *ClientMessage_StartResearch) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_StartResearch.ProtoReflect.Descriptor instead.
func (*ClientMessage_StartResearch) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 9}
}

func (x *ClientMessage_StartResearch) GetDiscovery() ResearchDiscovery {
	if x != nil {
		return x.Discovery
	}
	return ResearchDiscovery_WEBSITE
}

type ClientMessage_ReschoolMouse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MouseId string `protobuf:"bytes,1,opt,name=mouseId,proto3" json:"mouseId,omitempty"`
}

func (x *ClientMessage_ReschoolMouse) Reset() {
	*x = ClientMessage_ReschoolMouse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_ReschoolMouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_ReschoolMouse) ProtoMessage() {}

func (x *ClientMessage_ReschoolMouse) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_ReschoolMouse.ProtoReflect.Descriptor instead.
func (*ClientMessage_ReschoolMouse) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 10}
}

func (x *ClientMessage_ReschoolMouse) GetMouseId() string {
	if x != nil {
		return x.MouseId
	}
	return ""
}

type ClientMessage_RenameMouse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MouseId string `protobuf:"bytes,1,opt,name=mouseId,proto3" json:"mouseId,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ClientMessage_RenameMouse) Reset() {
	*x = ClientMessage_RenameMouse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_RenameMouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_RenameMouse) ProtoMessage() {}

func (x *ClientMessage_RenameMouse) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_RenameMouse.ProtoReflect.Descriptor instead.
func (*ClientMessage_RenameMouse) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 11}
}

func (x *ClientMessage_RenameMouse) GetMouseId() string {
	if x != nil {
		return x.MouseId
	}
	return ""
}

func (x *ClientMessage_RenameMouse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ClientMessage_OpenQuest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestId string `protobuf:"bytes,1,opt,name=questId,proto3" json:"questId,omitempty"`
}

func (x *ClientMessage_OpenQuest) Reset() {
	*x = ClientMessage_OpenQuest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_OpenQuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_OpenQuest) ProtoMessage() {}

func (x *ClientMessage_OpenQuest) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_OpenQuest.ProtoReflect.Descriptor instead.
func (*ClientMessage_OpenQuest) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 12}
}

func (x *ClientMessage_OpenQuest) GetQuestId() string {
	if x != nil {
		return x.QuestId
	}
	return ""
}

type ClientMessage_ClaimQuestReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestId           string `protobuf:"bytes,2,opt,name=questId,proto3" json:"questId,omitempty"`
	SelectedOneOfItem string `protobuf:"bytes,3,opt,name=selectedOneOfItem,proto3" json:"selectedOneOfItem,omitempty"`
}

func (x *ClientMessage_ClaimQuestReward) Reset() {
	*x = ClientMessage_ClaimQuestReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_ClaimQuestReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_ClaimQuestReward) ProtoMessage() {}

func (x *ClientMessage_ClaimQuestReward) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_ClaimQuestReward.ProtoReflect.Descriptor instead.
func (*ClientMessage_ClaimQuestReward) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 13}
}

func (x *ClientMessage_ClaimQuestReward) GetQuestId() string {
	if x != nil {
		return x.QuestId
	}
	return ""
}

func (x *ClientMessage_ClaimQuestReward) GetSelectedOneOfItem() string {
	if x != nil {
		return x.SelectedOneOfItem
	}
	return ""
}

type ClientMessage_CompleteQuest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestId string `protobuf:"bytes,1,opt,name=questId,proto3" json:"questId,omitempty"`
}

func (x *ClientMessage_CompleteQuest) Reset() {
	*x = ClientMessage_CompleteQuest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_CompleteQuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_CompleteQuest) ProtoMessage() {}

func (x *ClientMessage_CompleteQuest) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_CompleteQuest.ProtoReflect.Descriptor instead.
func (*ClientMessage_CompleteQuest) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 14}
}

func (x *ClientMessage_CompleteQuest) GetQuestId() string {
	if x != nil {
		return x.QuestId
	}
	return ""
}

type ClientMessage_ReportActivity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientMessage_ReportActivity) Reset() {
	*x = ClientMessage_ReportActivity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_ReportActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_ReportActivity) ProtoMessage() {}

func (x *ClientMessage_ReportActivity) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_ReportActivity.ProtoReflect.Descriptor instead.
func (*ClientMessage_ReportActivity) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 15}
}

type ClientMessage_SaveMouseAppearance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MouseId    string           `protobuf:"bytes,1,opt,name=mouseId,proto3" json:"mouseId,omitempty"`
	Appearance *MouseAppearance `protobuf:"bytes,2,opt,name=appearance,proto3" json:"appearance,omitempty"`
}

func (x *ClientMessage_SaveMouseAppearance) Reset() {
	*x = ClientMessage_SaveMouseAppearance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_SaveMouseAppearance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_SaveMouseAppearance) ProtoMessage() {}

func (x *ClientMessage_SaveMouseAppearance) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_SaveMouseAppearance.ProtoReflect.Descriptor instead.
func (*ClientMessage_SaveMouseAppearance) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 16}
}

func (x *ClientMessage_SaveMouseAppearance) GetMouseId() string {
	if x != nil {
		return x.MouseId
	}
	return ""
}

func (x *ClientMessage_SaveMouseAppearance) GetAppearance() *MouseAppearance {
	if x != nil {
		return x.Appearance
	}
	return nil
}

type ClientMessage_SetAmbassadorMouse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MouseId string `protobuf:"bytes,1,opt,name=mouseId,proto3" json:"mouseId,omitempty"`
}

func (x *ClientMessage_SetAmbassadorMouse) Reset() {
	*x = ClientMessage_SetAmbassadorMouse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_SetAmbassadorMouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_SetAmbassadorMouse) ProtoMessage() {}

func (x *ClientMessage_SetAmbassadorMouse) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_SetAmbassadorMouse.ProtoReflect.Descriptor instead.
func (*ClientMessage_SetAmbassadorMouse) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 17}
}

func (x *ClientMessage_SetAmbassadorMouse) GetMouseId() string {
	if x != nil {
		return x.MouseId
	}
	return ""
}

type ClientMessage_SetPizzaPrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PizzaPrice int32 `protobuf:"varint,1,opt,name=pizzaPrice,proto3" json:"pizzaPrice,omitempty"`
}

func (x *ClientMessage_SetPizzaPrice) Reset() {
	*x = ClientMessage_SetPizzaPrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_SetPizzaPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_SetPizzaPrice) ProtoMessage() {}

func (x *ClientMessage_SetPizzaPrice) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_SetPizzaPrice.ProtoReflect.Descriptor instead.
func (*ClientMessage_SetPizzaPrice) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 18}
}

func (x *ClientMessage_SetPizzaPrice) GetPizzaPrice() int32 {
	if x != nil {
		return x.PizzaPrice
	}
	return 0
}

type ClientMessage_BuyGeniusFlash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClientMessage_BuyGeniusFlash) Reset() {
	*x = ClientMessage_BuyGeniusFlash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_message_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_BuyGeniusFlash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_BuyGeniusFlash) ProtoMessage() {}

func (x *ClientMessage_BuyGeniusFlash) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_BuyGeniusFlash.ProtoReflect.Descriptor instead.
func (*ClientMessage_BuyGeniusFlash) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0, 19}
}

func (x *ClientMessage_BuyGeniusFlash) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_client_message_proto protoreflect.FileDescriptor

var file_client_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69,
	0x62, 0x65, 0x73, 0x1a, 0x10, 0x61, 0x70, 0x70, 0x65, 0x61, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfa, 0x14, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x03, 0x74, 0x61, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69,
	0x62, 0x65, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x54, 0x61, 0x70, 0x48, 0x00, 0x52, 0x03, 0x74, 0x61, 0x70, 0x12, 0x5c, 0x0a, 0x11,
	0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74,
	0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x11, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x56, 0x0a, 0x0f, 0x75, 0x70,
	0x67, 0x72, 0x61, 0x64, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65,
	0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x48,
	0x00, 0x52, 0x0f, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69,
	0x6e, 0x67, 0x12, 0x38, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x3b, 0x0a, 0x06,
	0x65, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70,
	0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x48,
	0x00, 0x52, 0x06, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x12, 0x38, 0x0a, 0x05, 0x73, 0x74, 0x65,
	0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61,
	0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x65, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74,
	0x65, 0x61, 0x6c, 0x12, 0x47, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74,
	0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x48, 0x00,
	0x52, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x4d, 0x0a, 0x0c,
	0x72, 0x61, 0x7a, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52,
	0x61, 0x7a, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x0c, 0x72,
	0x61, 0x7a, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x50, 0x0a, 0x0d, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x00, 0x52, 0x0d,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x5f, 0x0a,
	0x12, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x61, 0x7a, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x69, 0x6e, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x69, 0x7a, 0x7a,
	0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x61, 0x7a, 0x65,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x12, 0x63, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x52, 0x61, 0x7a, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x50,
	0x0a, 0x0d, 0x72, 0x65, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69,
	0x62, 0x65, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x4d, 0x6f, 0x75, 0x73, 0x65,
	0x12, 0x4a, 0x0a, 0x0b, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69,
	0x62, 0x65, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x0b, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x09,
	0x6f, 0x70, 0x65, 0x6e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4f, 0x70, 0x65, 0x6e,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x59, 0x0a, 0x10, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x70,
	0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x48, 0x00, 0x52, 0x10, 0x63, 0x6c, 0x61,
	0x69, 0x6d, 0x51, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x50, 0x0a,
	0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62,
	0x65, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x53, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74,
	0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x12, 0x62, 0x0a, 0x13, 0x73, 0x61, 0x76, 0x65, 0x4d, 0x6f, 0x75, 0x73,
	0x65, 0x41, 0x70, 0x70, 0x65, 0x61, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x12, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x61,
	0x76, 0x65, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x70, 0x70, 0x65, 0x61, 0x72, 0x61, 0x6e, 0x63,
	0x65, 0x48, 0x00, 0x52, 0x13, 0x73, 0x61, 0x76, 0x65, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x70,
	0x70, 0x65, 0x61, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x12, 0x73, 0x65, 0x74, 0x41,
	0x6d, 0x62, 0x61, 0x73, 0x73, 0x61, 0x64, 0x6f, 0x72, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x18, 0x13,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62,
	0x65, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x53, 0x65, 0x74, 0x41, 0x6d, 0x62, 0x61, 0x73, 0x73, 0x61, 0x64, 0x6f, 0x72, 0x4d, 0x6f,
	0x75, 0x73, 0x65, 0x48, 0x00, 0x52, 0x12, 0x73, 0x65, 0x74, 0x41, 0x6d, 0x62, 0x61, 0x73, 0x73,
	0x61, 0x64, 0x6f, 0x72, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x73, 0x65, 0x74,
	0x50, 0x69, 0x7a, 0x7a, 0x61, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x74,
	0x50, 0x69, 0x7a, 0x7a, 0x61, 0x50, 0x72, 0x69, 0x63, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x65,
	0x74, 0x50, 0x69, 0x7a, 0x7a, 0x61, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x0e, 0x62,
	0x75, 0x79, 0x47, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x18, 0x15, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65,
	0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x42, 0x75, 0x79, 0x47, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x48, 0x00,
	0x52, 0x0e, 0x62, 0x75, 0x79, 0x47, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x46, 0x6c, 0x61, 0x73, 0x68,
	0x1a, 0x1b, 0x0a, 0x03, 0x54, 0x61, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x1a, 0x5c, 0x0a,
	0x11, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69,
	0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x69, 0x7a,
	0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e,
	0x67, 0x52, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x1a, 0x27, 0x0a, 0x0f, 0x55,
	0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x6f, 0x74, 0x49, 0x64, 0x1a, 0x24, 0x0a, 0x0c, 0x52, 0x61, 0x7a, 0x65, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x1a, 0x2a, 0x0a, 0x12, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x52, 0x61, 0x7a, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x1a, 0x55, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x12,
	0x34, 0x0a, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73,
	0x2e, 0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x65, 0x64, 0x75, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x08, 0x0a,
	0x06, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x1a, 0x3b, 0x0a, 0x05, 0x53, 0x74, 0x65, 0x61, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x79, 0x1a, 0x1c, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x1a, 0x4d, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x12, 0x3c, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72,
	0x69, 0x62, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x52, 0x09, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x79, 0x1a, 0x29, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x4d, 0x6f, 0x75,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x1a, 0x3b, 0x0a, 0x0b,
	0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f,
	0x75, 0x73, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x25, 0x0a, 0x09, 0x4f, 0x70, 0x65,
	0x6e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x1a, 0x5a, 0x0a, 0x10, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x51, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x2c,
	0x0a, 0x11, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x49,
	0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x29, 0x0a, 0x0d,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x1a, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x1a, 0x6d, 0x0a, 0x13, 0x53, 0x61, 0x76,
	0x65, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x70, 0x70, 0x65, 0x61, 0x72, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0a, 0x61, 0x70,
	0x70, 0x65, 0x61, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x75,
	0x73, 0x65, 0x41, 0x70, 0x70, 0x65, 0x61, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x0a, 0x61, 0x70,
	0x70, 0x65, 0x61, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x2e, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x41,
	0x6d, 0x62, 0x61, 0x73, 0x73, 0x61, 0x64, 0x6f, 0x72, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x1a, 0x2f, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x50,
	0x69, 0x7a, 0x7a, 0x61, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x69, 0x7a,
	0x7a, 0x61, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70,
	0x69, 0x7a, 0x7a, 0x61, 0x50, 0x72, 0x69, 0x63, 0x65, 0x1a, 0x20, 0x0a, 0x0e, 0x42, 0x75, 0x79,
	0x47, 0x65, 0x6e, 0x69, 0x75, 0x73, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x66, 0x6e, 0x61, 0x74, 0x74, 0x65, 0x2f, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x2d, 0x74,
	0x72, 0x69, 0x62, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67,
	0x61, 0x6d, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_client_message_proto_rawDescOnce sync.Once
	file_client_message_proto_rawDescData = file_client_message_proto_rawDesc
)

func file_client_message_proto_rawDescGZIP() []byte {
	file_client_message_proto_rawDescOnce.Do(func() {
		file_client_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_message_proto_rawDescData)
	})
	return file_client_message_proto_rawDescData
}

var file_client_message_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_client_message_proto_goTypes = []interface{}{
	(*ClientMessage)(nil),                     // 0: pizzatribes.ClientMessage
	(*ClientMessage_Tap)(nil),                 // 1: pizzatribes.ClientMessage.Tap
	(*ClientMessage_ConstructBuilding)(nil),   // 2: pizzatribes.ClientMessage.ConstructBuilding
	(*ClientMessage_UpgradeBuilding)(nil),     // 3: pizzatribes.ClientMessage.UpgradeBuilding
	(*ClientMessage_RazeBuilding)(nil),        // 4: pizzatribes.ClientMessage.RazeBuilding
	(*ClientMessage_CancelRazeBuilding)(nil),  // 5: pizzatribes.ClientMessage.CancelRazeBuilding
	(*ClientMessage_Train)(nil),               // 6: pizzatribes.ClientMessage.Train
	(*ClientMessage_Expand)(nil),              // 7: pizzatribes.ClientMessage.Expand
	(*ClientMessage_Steal)(nil),               // 8: pizzatribes.ClientMessage.Steal
	(*ClientMessage_ReadReport)(nil),          // 9: pizzatribes.ClientMessage.ReadReport
	(*ClientMessage_StartResearch)(nil),       // 10: pizzatribes.ClientMessage.StartResearch
	(*ClientMessage_ReschoolMouse)(nil),       // 11: pizzatribes.ClientMessage.ReschoolMouse
	(*ClientMessage_RenameMouse)(nil),         // 12: pizzatribes.ClientMessage.RenameMouse
	(*ClientMessage_OpenQuest)(nil),           // 13: pizzatribes.ClientMessage.OpenQuest
	(*ClientMessage_ClaimQuestReward)(nil),    // 14: pizzatribes.ClientMessage.ClaimQuestReward
	(*ClientMessage_CompleteQuest)(nil),       // 15: pizzatribes.ClientMessage.CompleteQuest
	(*ClientMessage_ReportActivity)(nil),      // 16: pizzatribes.ClientMessage.ReportActivity
	(*ClientMessage_SaveMouseAppearance)(nil), // 17: pizzatribes.ClientMessage.SaveMouseAppearance
	(*ClientMessage_SetAmbassadorMouse)(nil),  // 18: pizzatribes.ClientMessage.SetAmbassadorMouse
	(*ClientMessage_SetPizzaPrice)(nil),       // 19: pizzatribes.ClientMessage.SetPizzaPrice
	(*ClientMessage_BuyGeniusFlash)(nil),      // 20: pizzatribes.ClientMessage.BuyGeniusFlash
	(Building)(0),                             // 21: pizzatribes.Building
	(Education)(0),                            // 22: pizzatribes.Education
	(ResearchDiscovery)(0),                    // 23: pizzatribes.ResearchDiscovery
	(*MouseAppearance)(nil),                   // 24: pizzatribes.MouseAppearance
}
var file_client_message_proto_depIdxs = []int32{
	1,  // 0: pizzatribes.ClientMessage.tap:type_name -> pizzatribes.ClientMessage.Tap
	2,  // 1: pizzatribes.ClientMessage.constructBuilding:type_name -> pizzatribes.ClientMessage.ConstructBuilding
	3,  // 2: pizzatribes.ClientMessage.upgradeBuilding:type_name -> pizzatribes.ClientMessage.UpgradeBuilding
	6,  // 3: pizzatribes.ClientMessage.train:type_name -> pizzatribes.ClientMessage.Train
	7,  // 4: pizzatribes.ClientMessage.expand:type_name -> pizzatribes.ClientMessage.Expand
	8,  // 5: pizzatribes.ClientMessage.steal:type_name -> pizzatribes.ClientMessage.Steal
	9,  // 6: pizzatribes.ClientMessage.readReport:type_name -> pizzatribes.ClientMessage.ReadReport
	4,  // 7: pizzatribes.ClientMessage.razeBuilding:type_name -> pizzatribes.ClientMessage.RazeBuilding
	10, // 8: pizzatribes.ClientMessage.startResearch:type_name -> pizzatribes.ClientMessage.StartResearch
	5,  // 9: pizzatribes.ClientMessage.cancelRazeBuilding:type_name -> pizzatribes.ClientMessage.CancelRazeBuilding
	11, // 10: pizzatribes.ClientMessage.reschoolMouse:type_name -> pizzatribes.ClientMessage.ReschoolMouse
	12, // 11: pizzatribes.ClientMessage.renameMouse:type_name -> pizzatribes.ClientMessage.RenameMouse
	13, // 12: pizzatribes.ClientMessage.openQuest:type_name -> pizzatribes.ClientMessage.OpenQuest
	14, // 13: pizzatribes.ClientMessage.claimQuestReward:type_name -> pizzatribes.ClientMessage.ClaimQuestReward
	15, // 14: pizzatribes.ClientMessage.completeQuest:type_name -> pizzatribes.ClientMessage.CompleteQuest
	16, // 15: pizzatribes.ClientMessage.reportActivity:type_name -> pizzatribes.ClientMessage.ReportActivity
	17, // 16: pizzatribes.ClientMessage.saveMouseAppearance:type_name -> pizzatribes.ClientMessage.SaveMouseAppearance
	18, // 17: pizzatribes.ClientMessage.setAmbassadorMouse:type_name -> pizzatribes.ClientMessage.SetAmbassadorMouse
	19, // 18: pizzatribes.ClientMessage.setPizzaPrice:type_name -> pizzatribes.ClientMessage.SetPizzaPrice
	20, // 19: pizzatribes.ClientMessage.buyGeniusFlash:type_name -> pizzatribes.ClientMessage.BuyGeniusFlash
	21, // 20: pizzatribes.ClientMessage.ConstructBuilding.building:type_name -> pizzatribes.Building
	22, // 21: pizzatribes.ClientMessage.Train.education:type_name -> pizzatribes.Education
	23, // 22: pizzatribes.ClientMessage.StartResearch.discovery:type_name -> pizzatribes.ResearchDiscovery
	24, // 23: pizzatribes.ClientMessage.SaveMouseAppearance.appearance:type_name -> pizzatribes.MouseAppearance
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_client_message_proto_init() }
func file_client_message_proto_init() {
	if File_client_message_proto != nil {
		return
	}
	file_appearance_proto_init()
	file_education_proto_init()
	file_building_proto_init()
	file_research_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_client_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_Tap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_ConstructBuilding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_UpgradeBuilding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_RazeBuilding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_CancelRazeBuilding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_Train); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_Expand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_Steal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_ReadReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_StartResearch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_ReschoolMouse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_RenameMouse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_OpenQuest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_ClaimQuestReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_CompleteQuest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_ReportActivity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_SaveMouseAppearance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_SetAmbassadorMouse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_SetPizzaPrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_message_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_BuyGeniusFlash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_client_message_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ClientMessage_Tap_)(nil),
		(*ClientMessage_ConstructBuilding_)(nil),
		(*ClientMessage_UpgradeBuilding_)(nil),
		(*ClientMessage_Train_)(nil),
		(*ClientMessage_Expand_)(nil),
		(*ClientMessage_Steal_)(nil),
		(*ClientMessage_ReadReport_)(nil),
		(*ClientMessage_RazeBuilding_)(nil),
		(*ClientMessage_StartResearch_)(nil),
		(*ClientMessage_CancelRazeBuilding_)(nil),
		(*ClientMessage_ReschoolMouse_)(nil),
		(*ClientMessage_RenameMouse_)(nil),
		(*ClientMessage_OpenQuest_)(nil),
		(*ClientMessage_ClaimQuestReward_)(nil),
		(*ClientMessage_CompleteQuest_)(nil),
		(*ClientMessage_ReportActivity_)(nil),
		(*ClientMessage_SaveMouseAppearance_)(nil),
		(*ClientMessage_SetAmbassadorMouse_)(nil),
		(*ClientMessage_SetPizzaPrice_)(nil),
		(*ClientMessage_BuyGeniusFlash_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_message_proto_goTypes,
		DependencyIndexes: file_client_message_proto_depIdxs,
		MessageInfos:      file_client_message_proto_msgTypes,
	}.Build()
	File_client_message_proto = out.File
	file_client_message_proto_rawDesc = nil
	file_client_message_proto_goTypes = nil
	file_client_message_proto_depIdxs = nil
}
