// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.21.4
// source: education.proto

package models

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Education int32

const (
	Education_CHEF       Education = 0
	Education_SALESMOUSE Education = 1
	Education_GUARD      Education = 2
	Education_THIEF      Education = 3
	Education_PUBLICIST  Education = 4
)

// Enum value maps for Education.
var (
	Education_name = map[int32]string{
		0: "CHEF",
		1: "SALESMOUSE",
		2: "GUARD",
		3: "THIEF",
		4: "PUBLICIST",
	}
	Education_value = map[string]int32{
		"CHEF":       0,
		"SALESMOUSE": 1,
		"GUARD":      2,
		"THIEF":      3,
		"PUBLICIST":  4,
	}
)

func (x Education) Enum() *Education {
	p := new(Education)
	*p = x
	return p
}

func (x Education) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Education) Descriptor() protoreflect.EnumDescriptor {
	return file_education_proto_enumTypes[0].Descriptor()
}

func (Education) Type() protoreflect.EnumType {
	return &file_education_proto_enumTypes[0]
}

func (x Education) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Education.Descriptor instead.
func (Education) EnumDescriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{0}
}

var File_education_proto protoreflect.FileDescriptor

var file_education_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2a, 0x4a,
	0x0a, 0x09, 0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a, 0x04, 0x43,
	0x48, 0x45, 0x46, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x41, 0x4c, 0x45, 0x53, 0x4d, 0x4f,
	0x55, 0x53, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x55, 0x41, 0x52, 0x44, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x54, 0x48, 0x49, 0x45, 0x46, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x50,
	0x55, 0x42, 0x4c, 0x49, 0x43, 0x49, 0x53, 0x54, 0x10, 0x04, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6e, 0x61, 0x74, 0x74, 0x65, 0x2f,
	0x70, 0x69, 0x7a, 0x7a, 0x61, 0x2d, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_education_proto_rawDescOnce sync.Once
	file_education_proto_rawDescData = file_education_proto_rawDesc
)

func file_education_proto_rawDescGZIP() []byte {
	file_education_proto_rawDescOnce.Do(func() {
		file_education_proto_rawDescData = protoimpl.X.CompressGZIP(file_education_proto_rawDescData)
	})
	return file_education_proto_rawDescData
}

var file_education_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_education_proto_goTypes = []interface{}{
	(Education)(0), // 0: pizzatribes.Education
}
var file_education_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_education_proto_init() }
func file_education_proto_init() {
	if File_education_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_education_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_education_proto_goTypes,
		DependencyIndexes: file_education_proto_depIdxs,
		EnumInfos:         file_education_proto_enumTypes,
	}.Build()
	File_education_proto = out.File
	file_education_proto_rawDesc = nil
	file_education_proto_goTypes = nil
	file_education_proto_depIdxs = nil
}
