// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.21.4
// source: quest.proto

package models

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Quest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string        `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Reward      *Quest_Reward `protobuf:"bytes,4,opt,name=reward,proto3" json:"reward,omitempty"`
	Order       int32         `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *Quest) Reset() {
	*x = Quest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quest) ProtoMessage() {}

func (x *Quest) ProtoReflect() protoreflect.Message {
	mi := &file_quest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quest.ProtoReflect.Descriptor instead.
func (*Quest) Descriptor() ([]byte, []int) {
	return file_quest_proto_rawDescGZIP(), []int{0}
}

func (x *Quest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Quest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Quest) GetReward() *Quest_Reward {
	if x != nil {
		return x.Reward
	}
	return nil
}

func (x *Quest) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type Quest_Reward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coins      int32    `protobuf:"varint,1,opt,name=coins,proto3" json:"coins,omitempty"`
	Pizzas     int32    `protobuf:"varint,2,opt,name=pizzas,proto3" json:"pizzas,omitempty"`
	OneOfItems []string `protobuf:"bytes,3,rep,name=oneOfItems,proto3" json:"oneOfItems,omitempty"`
}

func (x *Quest_Reward) Reset() {
	*x = Quest_Reward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quest_Reward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quest_Reward) ProtoMessage() {}

func (x *Quest_Reward) ProtoReflect() protoreflect.Message {
	mi := &file_quest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quest_Reward.ProtoReflect.Descriptor instead.
func (*Quest_Reward) Descriptor() ([]byte, []int) {
	return file_quest_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Quest_Reward) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *Quest_Reward) GetPizzas() int32 {
	if x != nil {
		return x.Pizzas
	}
	return 0
}

func (x *Quest_Reward) GetOneOfItems() []string {
	if x != nil {
		return x.OneOfItems
	}
	return nil
}

var File_quest_proto protoreflect.FileDescriptor

var file_quest_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70,
	0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x22, 0xf0, 0x01, 0x0a, 0x05, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x06,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70,
	0x69, 0x7a, 0x7a, 0x61, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x56, 0x0a, 0x06, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6f, 0x69, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x6f, 0x6e, 0x65, 0x4f, 0x66, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x6f, 0x6e, 0x65, 0x4f, 0x66, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x35, 0x5a,
	0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6e, 0x61, 0x74,
	0x74, 0x65, 0x2f, 0x70, 0x69, 0x7a, 0x7a, 0x61, 0x2d, 0x74, 0x72, 0x69, 0x62, 0x65, 0x73, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quest_proto_rawDescOnce sync.Once
	file_quest_proto_rawDescData = file_quest_proto_rawDesc
)

func file_quest_proto_rawDescGZIP() []byte {
	file_quest_proto_rawDescOnce.Do(func() {
		file_quest_proto_rawDescData = protoimpl.X.CompressGZIP(file_quest_proto_rawDescData)
	})
	return file_quest_proto_rawDescData
}

var file_quest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_quest_proto_goTypes = []interface{}{
	(*Quest)(nil),        // 0: pizzatribes.Quest
	(*Quest_Reward)(nil), // 1: pizzatribes.Quest.Reward
}
var file_quest_proto_depIdxs = []int32{
	1, // 0: pizzatribes.Quest.reward:type_name -> pizzatribes.Quest.Reward
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_quest_proto_init() }
func file_quest_proto_init() {
	if File_quest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quest_Reward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quest_proto_goTypes,
		DependencyIndexes: file_quest_proto_depIdxs,
		MessageInfos:      file_quest_proto_msgTypes,
	}.Build()
	File_quest_proto = out.File
	file_quest_proto_rawDesc = nil
	file_quest_proto_goTypes = nil
	file_quest_proto_depIdxs = nil
}
