#!/bin/sh
protoc > /dev/null 2>&1 # Installs protoc
protoc \
	--plugin ./node_modules/.bin/protoc-gen-dump \
	--plugin ./node_modules/.bin/protoc-gen-ts \
	--ts_out src/generated/ \
	--ts_opt long_type_string \
	--proto_path ./node_modules/@protobuf-ts/plugin \
	--proto_path ../protos/ \
	../protos/*.proto
