#!/bin/sh
protoc \
	--plugin ./node_modules/.bin/protoc-gen-dump \
	--plugin ./node_modules/.bin/protoc-gen-ts \
	--ts_out src/generated/ \
	--proto_path ./node_modules/@protobuf-ts/plugin \
	--proto_path ../proto/ \
	../proto/client_message.proto
