// Code generated by jtd-codegen for Go v0.2.1. DO NOT EDIT.

package gamedata

type GameData struct {
	Buildings []BuildingInfo `json:"buildings"`

	Educations []EducationInfo `json:"educations"`

	Quests []Quest `json:"quests"`

	ResearchTracks []ResearchTrack `json:"researchTracks"`
}

type BuildingInfoLevelInfoEmployer struct {
	MaxWorkforce int32 `json:"maxWorkforce"`
}

type BuildingInfoLevelInfoResidence struct {
	Beds int32 `json:"beds"`
}

type BuildingInfoLevelInfo struct {
	ConstructionTime int32 `json:"constructionTime"`

	Cost int32 `json:"cost"`

	FirstConstructionTime *int32 `json:"firstConstructionTime"`

	FirstCost *int32 `json:"firstCost"`

	Employer *BuildingInfoLevelInfoEmployer `json:"employer,omitempty"`

	Residence *BuildingInfoLevelInfoResidence `json:"residence,omitempty"`
}

type BuildingInfo struct {
	ID string `json:"id"`

	LevelInfos []BuildingInfoLevelInfo `json:"levelInfos"`

	MaxCount *int32 `json:"maxCount"`

	Title string `json:"title"`

	TitlePlural string `json:"titlePlural"`
}

type EducationInfo struct {
	Cost int32 `json:"cost"`

	Employer *string `json:"employer"`

	ID string `json:"id"`

	Title string `json:"title"`

	TitlePlural string `json:"titlePlural"`

	TrainTime int32 `json:"trainTime"`
}

type QuestReward struct {
	Coins int32 `json:"coins"`

	Pizzas int32 `json:"pizzas"`
}

type Quest struct {
	Description string `json:"description"`

	ID string `json:"id"`

	Reward QuestReward `json:"reward"`

	Title string `json:"title"`
}

type ResearchNode struct {
	Cost int32 `json:"cost"`

	Discovery string `json:"discovery"`

	Nodes []ResearchNode `json:"nodes"`

	ResearchTime int32 `json:"researchTime"`

	Title string `json:"title"`
}

type ResearchTrack struct {
	RootNode ResearchNode `json:"rootNode"`

	Title string `json:"title"`
}
