name: Docker Images

on:
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push - API
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          target: api
          push: true
          tags: ghcr.io/fnatte/pizza-tribes-api:latest
      -
        name: Build and push - Updater
        id: docker_build_updater
        uses: docker/build-push-action@v2
        with:
          target: updater
          push: true
          tags: ghcr.io/fnatte/pizza-tribes-updater:latest
      -
        name: Build and push - Worker
        id: docker_build_worker
        uses: docker/build-push-action@v2
        with:
          target: worker
          push: true
          tags: ghcr.io/fnatte/pizza-tribes-worker:latest
      -
        name: Build and push - Migrator
        id: docker_build_migrator
        uses: docker/build-push-action@v2
        with:
          target: migrator
          push: true
          tags: ghcr.io/fnatte/pizza-tribes-migrator:latest
      -
        name: Build and push - Web app
        id: docker_build_webapp
        uses: docker/build-push-action@v2
        with:
          target: webapp
          push: true
          tags: ghcr.io/fnatte/pizza-tribes-webapp:latest
      -
        name: Build and push - Front
        id: docker_build_front
        uses: docker/build-push-action@v2
        with:
          target: front
          push: true
          tags: ghcr.io/fnatte/pizza-tribes-front:latest

