name: Web App Docker Image

on:
  push:
    branches: [main, actions]
    paths-ignore:
      - "README.md"
      - "cmd/**"
      - "internal/**"
  pull_request:
    branches: [main]

jobs:
  build-and-push-webapp-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push - Web app
        id: docker_build_webapp
        uses: docker/build-push-action@v2
        with:
          target: webapp
          push: true
          tags: ghcr.io/fnatte/pizza-tribes-webapp:latest
